all: piece.o maillon.o liste.o maillonc.o listec.o coups.o coordonnee.o partie.o main.o
	gcc -Wall -ansi -pedantic piece.o maillon.o liste.o maillonc.o listec.o coups.o coordonnee.o partie.o main.o -o jeudechec

piece.o: piece.c
	gcc -c -Wall -ansi -pedantic piece.c

maillon.o: maillon.c
	gcc -c -Wall -ansi -pedantic maillon.c

liste.o: liste.c
	gcc -c -Wall -ansi -pedantic liste.c

maillonc.o: maillonc.c
	gcc -c -Wall -ansi -pedantic maillonc.c

listec.o: listec.c
	gcc -c -Wall -ansi -pedantic listec.c

coups.o: coups.c
	gcc -c -Wall -ansi -pedantic coups.c

coordonnee.o: coordonnee.c
	gcc -c -Wall -ansi -pedantic coordonnee.c

partie.o: partie.c
	gcc -c -Wall -ansi -pedantic partie.c

main.o: main.c
	gcc -c -Wall -ansi -pedantic main.c


